### ISSUE TITLE
 'ZooModelsManifest' object has no attribute 'has_tag'

### ISSUE THREAD

**Issue by albi-sema** [jacobmarks/clustering-plugin#1]
This error is thrown as soon as I start typing something for Run key.

if model.has_tag("embeddings"):
       ^^^^^^^^^^^^^
AttributeError: 'ZooModelsManifest' object has no attribute 'has_tag'

**Comment by thgie** [comment]
Same. I believe fiftyone made some updates, that are not reflected in this plugin yet.

If it's urgent: Uncomment lines 343-345 in `~/fiftyone/__plugins__/@jacobmarks/clustering/__init__.py`. This works if you don't need the model option and base your clustering on embeddings. I also had to fill out the optional `Cluster field` input, without which I run into another error.

**Comment by jacobmarks** [comment]
Hey @thgie and @albi-sema , thanks for uncovering this. It looks like the new remote zoo models capability in FiftyOne 1.0.0 was the culprit. This should be fixed now. Closing for now, but let me know if you still experience this problem
